# Generated by Django 5.2.1 on 2025-07-13 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCM Token',
                'verbose_name_plural': 'FCM Tokens',
                'db_table': 'fcm_tokens',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Başarılı'), ('failed', 'Başarısız'), ('pending', 'Beklemede')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('fcm_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='push_notifications.fcmtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.DeleteModel(
            name='PushToken',
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['user', 'is_active'], name='fcm_tokens_user_id_356d47_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['fcm_token'], name='fcm_tokens_fcm_tok_f40623_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('user', 'platform')},
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_9d8bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['sent_at'], name='notificatio_sent_at_85d1ed_idx'),
        ),
    ]
