# Generated by Django 5.2 on 2025-04-11 11:08

import apps.comment.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.comment.models.comment_image_upload_path, verbose_name='Resim')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıralama')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='comment.comment', verbose_name='Yorum')),
            ],
            options={
                'verbose_name': 'Yorum Resmi',
                'verbose_name_plural': 'Yorum Resimleri',
                'ordering': ['order'],
            },
        ),
    ]
