# Generated by Django 5.2.1 on 2025-06-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_comment_com_content_0e9f81_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_com_content_0e9f81_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_com_user_id_d2a938_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_com_parent__bee200_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_com_is_acti_213ac3_idx',
        ),
    ]
