# Generated by Django 5.2.1 on 2025-07-14 23:22

import apps.comment.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_comment_comment_com_content_0e9f81_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dosya Boyutu (bytes)'),
        ),
        migrations.AddField(
            model_name='commentimage',
            name='format',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Format (WEBP/JPEG)'),
        ),
        migrations.AddField(
            model_name='commentimage',
            name='hash',
            field=models.CharField(blank=True, help_text='Duplicate detection için', max_length=32, null=True, verbose_name='MD5 Hash'),
        ),
        migrations.AddField(
            model_name='commentimage',
            name='original_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orijinal Yükseklik'),
        ),
        migrations.AddField(
            model_name='commentimage',
            name='original_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orijinal Genişlik'),
        ),
        migrations.AddField(
            model_name='commentimage',
            name='processed',
            field=models.BooleanField(default=False, help_text='Resim backend tarafından işlendi mi?', verbose_name='İşlenmiş'),
        ),
        migrations.AddField(
            model_name='commentimage',
            name='small',
            field=models.ImageField(blank=True, null=True, upload_to=apps.comment.models.comment_image_upload_path, verbose_name='Small (300x300)'),
        ),
        migrations.AddField(
            model_name='commentimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.comment.models.comment_image_upload_path, verbose_name='Thumbnail (150x150)'),
        ),
        migrations.AlterField(
            model_name='commentimage',
            name='image',
            field=models.ImageField(upload_to=apps.comment.models.comment_image_upload_path, verbose_name='Orijinal Resim'),
        ),
        migrations.AddIndex(
            model_name='commentimage',
            index=models.Index(fields=['hash'], name='comment_com_hash_a28ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='commentimage',
            index=models.Index(fields=['processed'], name='comment_com_process_d72a09_idx'),
        ),
    ]
