# Generated by Django 5.2 on 2025-04-12 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemberFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Soyad')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanıcı Adı')),
                ('is_verified', models.BooleanField(blank=True, null=True, verbose_name='Doğrulanmış Hesap')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Son Kullanım Tarihi')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataset.department', verbose_name='Bölüm')),
                ('graduation_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataset.graduationstatus', verbose_name='Mezuniyet Durumu')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataset.university', verbose_name='Üniversite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_filter', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Üye Filtresi',
                'verbose_name_plural': 'Kullanıcı Üye Filtreleri',
            },
        ),
    ]
