# Generated by Django 5.2 on 2025-04-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermemberfilter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usermemberfilter',
            name='username',
        ),
    ]
