# Generated by Django 5.2.1 on 2025-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message_privacy',
            field=models.CharField(choices=[('none', 'Hiç Kimse'), ('followers', 'Sadece Takipçilerim'), ('everyone', 'Herkes')], default='everyone', max_length=10, verbose_name='Mesaj Gizliliği'),
        ),
    ]
