# Generated by Django 5.2.1 on 2025-05-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_message_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-posta Doğrulama Gönderim Zamanı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True, verbose_name='E-posta Doğrulama Kodu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='E-posta Doğrulandı'),
        ),
    ]
