# Generated by Django 5.2.1 on 2025-06-10 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0001_initial'),
        ('profiles', '0003_profile_email_verification_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_private'], name='idx_profile_is_private'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['email_verified'], name='idx_profile_email_verified'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['university', 'department'], name='idx_profile_uni_dept'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_verified'], name='idx_profile_is_verified'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['message_privacy'], name='idx_profile_msg_privacy'),
        ),
    ]
