# Generated by Django 5.2.1 on 2025-06-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_idx_profile_is_private_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='idx_profile_is_private',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='idx_profile_email_verified',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='idx_profile_uni_dept',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='idx_profile_is_verified',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='idx_profile_msg_privacy',
        ),
    ]
