# Generated by Django 5.2.1 on 2025-06-10 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0001_initial'),
        ('profiles', '0005_remove_profile_idx_profile_is_private_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='profiles_pr_user_id_3364d1_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_private'], name='profiles_pr_is_priv_5ff137_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_verified'], name='profiles_pr_is_veri_eed514_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['university'], name='profiles_pr_univers_01a24e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['department'], name='profiles_pr_departm_2d578d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['university', 'department'], name='profiles_pr_univers_227ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['email_verified'], name='profiles_pr_email_v_dbd533_idx'),
        ),
    ]
