# Generated by Django 5.2.1 on 2025-06-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_profiles_pr_user_id_3364d1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_user_id_3364d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_is_priv_5ff137_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_is_veri_eed514_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_univers_01a24e_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_departm_2d578d_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_univers_227ae8_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_email_v_dbd533_idx',
        ),
    ]
