# Generated by Django 5.2.1 on 2025-07-14 23:22

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_profiles_pr_user_id_3364d1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_medium',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.profiles.models.avatar_upload_path, verbose_name='Avatar Medium (300x300)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_processed',
            field=models.BooleanField(default=False, help_text='Avatar backend tarafından işlendi mi?', verbose_name='Avatar İşlenmiş'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.profiles.models.avatar_upload_path, verbose_name='Avatar Thumbnail (150x150)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.profiles.models.avatar_upload_path, verbose_name='Profil Fotoğrafı (Orijinal)'),
        ),
    ]
