# Generated by Django 5.2.1 on 2025-07-18 14:00

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_avatar_medium_profile_avatar_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_large',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.profiles.models.avatar_upload_path, verbose_name='Avatar Large (600x600)'),
        ),
    ]
