# Generated by Django 5.2.1 on 2025-06-10 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='bookmark_bo_user_id_096f45_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['content_type', 'object_id', '-created_at'], name='bookmark_bo_content_a8b45f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', '-created_at'], name='bookmark_bo_user_id_195b03_idx'),
        ),
    ]
