# Generated by Django 5.2.1 on 2025-06-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_bookmark_bo_user_id_096f45_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bookmark_bo_user_id_096f45_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bookmark_bo_content_a8b45f_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bookmark_bo_user_id_195b03_idx',
        ),
    ]
