# Generated by Django 5.2.1 on 2025-06-11 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_alter_bookmark_created_at_alter_bookmark_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bookmark_bo_user_id_195b03_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bookmark_bo_content_a8b45f_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bookmark_bo_user_id_92334d_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bookmark_bo_created_147093_idx',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Zamanı'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Nesne ID'),
        ),
    ]
