# Generated by Django 5.2.1 on 2025-06-11 21:58

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_remove_bookmark_bookmark_bo_user_id_195b03_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Zamanı'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Nesne ID'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='bookmark_bo_user_id_096f45_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'created_at'], name='bookmark_bo_user_id_0027f8_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='bookmark_bo_content_164ede_idx'),
        ),
    ]
