# Generated by Django 5.2.1 on 2025-06-11 23:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_alter_bookmark_created_at_alter_bookmark_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bookmark_bo_user_id_096f45_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bookmark_bo_user_id_0027f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='bookmark_bo_content_164ede_idx',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Zamanı'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Nesne ID'),
        ),
    ]
