# Generated by Django 5.2.1 on 2025-07-17 22:12

import apps.confession.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfessionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'İtiraf Kategorisi',
                'verbose_name_plural': 'İtiraf Kategorileri',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='confession__name_980ef2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfessionFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Son Kullanım Tarihi')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='confession.confessioncategory', verbose_name='Kategori')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataset.university', verbose_name='Üniversite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confession_filter', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı İtiraf Filtresi',
                'verbose_name_plural': 'Kullanıcı İtiraf Filtreleri',
            },
        ),
        migrations.CreateModel(
            name='ConfessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='İtiraf Metni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_privacy', models.BooleanField(default=True, verbose_name='Gizlilik')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confessions', to='confession.confessioncategory', verbose_name='Kategori')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.university', verbose_name='Üniversite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confessions', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'İtiraf',
                'verbose_name_plural': 'İtiraflar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfessionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.confession.models.confession_image_upload_path, verbose_name='Orijinal Resim')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.confession.models.confession_image_upload_path, verbose_name='Thumbnail (150x150)')),
                ('medium', models.ImageField(blank=True, null=True, upload_to=apps.confession.models.confession_image_upload_path, verbose_name='Medium (600x600)')),
                ('large', models.ImageField(blank=True, null=True, upload_to=apps.confession.models.confession_image_upload_path, verbose_name='Large (1200x1200)')),
                ('original_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Orijinal Genişlik')),
                ('original_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Orijinal Yükseklik')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dosya Boyutu (bytes)')),
                ('format', models.CharField(blank=True, max_length=10, null=True, verbose_name='Format (WEBP/JPEG)')),
                ('hash', models.CharField(blank=True, help_text='Duplicate detection için', max_length=32, null=True, verbose_name='MD5 Hash')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıralama')),
                ('processed', models.BooleanField(default=False, help_text='Resim backend tarafından işlendi mi?', verbose_name='İşlenmiş')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_images', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='confession.confessionmodel', verbose_name='İtiraf')),
            ],
            options={
                'verbose_name': 'İtiraf Resmi',
                'verbose_name_plural': 'İtiraf Resimleri',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='confessionmodel',
            index=models.Index(fields=['created_at'], name='confession__created_04d6df_idx'),
        ),
        migrations.AddIndex(
            model_name='confessionmodel',
            index=models.Index(fields=['category', 'created_at'], name='confession__categor_faaaab_idx'),
        ),
        migrations.AddIndex(
            model_name='confessionmodel',
            index=models.Index(fields=['university', 'created_at'], name='confession__univers_0af4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='confessionmodel',
            index=models.Index(fields=['user', 'created_at'], name='confession__user_id_032554_idx'),
        ),
        migrations.AddIndex(
            model_name='confessionmodel',
            index=models.Index(fields=['is_active', 'created_at'], name='confession__is_acti_4c7406_idx'),
        ),
        migrations.AddIndex(
            model_name='confessionmodel',
            index=models.Index(fields=['is_privacy', 'created_at'], name='confession__is_priv_9d9014_idx'),
        ),
        migrations.AddIndex(
            model_name='confessionmodel',
            index=models.Index(fields=['university', 'is_privacy', 'created_at'], name='confession__univers_ddc6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='confessionimage',
            index=models.Index(fields=['hash'], name='confession__hash_b6b30f_idx'),
        ),
        migrations.AddIndex(
            model_name='confessionimage',
            index=models.Index(fields=['processed'], name='confession__process_6f8bb2_idx'),
        ),
    ]
