# Generated by Django 5.1.1 on 2025-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_userpostfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostfilter',
            name='posts_type',
            field=models.CharField(choices=[('all', 'Bütün Gönderiler'), ('following', 'Sadece Takip Ettiklerim'), ('verified', 'Sadece Doğrulanmış Hesaplar')], default='all', max_length=10, verbose_name='Gönderi Tipi'),
        ),
    ]
