# Generated by Django 5.2.1 on 2025-06-10 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_author_post_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hashtag',
            index=models.Index(fields=['name'], name='idx_hashtag_name'),
        ),
        migrations.AddIndex(
            model_name='hashtag',
            index=models.Index(fields=['created_at'], name='idx_hashtag_created'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='idx_post_user'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='idx_post_created'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'created_at'], name='idx_post_user_created'),
        ),
    ]
