# Generated by Django 5.2.1 on 2025-06-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_hashtag_idx_hashtag_name_hashtag_idx_hashtag_created_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hashtag',
            name='idx_hashtag_name',
        ),
        migrations.RemoveIndex(
            model_name='hashtag',
            name='idx_hashtag_created',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='idx_post_user',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='idx_post_created',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='idx_post_user_created',
        ),
    ]
