# Generated by Django 5.2.1 on 2025-06-10 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0001_initial'),
        ('post', '0007_remove_hashtag_idx_hashtag_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hashtag',
            index=models.Index(fields=['name'], name='post_hashta_name_ac8446_idx'),
        ),
        migrations.AddIndex(
            model_name='hashtag',
            index=models.Index(fields=['-created_at'], name='post_hashta_created_82297b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='post_post_user_id_7a756f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='post_post_created_910bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='post_post_user_id_57d352_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='post_post_created_0713d7_idx'),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post', 'order'], name='post_postim_post_id_c0581b_idx'),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post'], name='post_postim_post_id_a475e2_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostfilter',
            index=models.Index(fields=['user'], name='post_userpo_user_id_041c31_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostfilter',
            index=models.Index(fields=['posts_type'], name='post_userpo_posts_t_c75266_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostfilter',
            index=models.Index(fields=['university'], name='post_userpo_univers_034f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostfilter',
            index=models.Index(fields=['department'], name='post_userpo_departm_a9231f_idx'),
        ),
    ]
