# Generated by Django 5.2.1 on 2025-06-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_hashtag_post_hashta_name_ac8446_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hashtag',
            name='post_hashta_name_ac8446_idx',
        ),
        migrations.RemoveIndex(
            model_name='hashtag',
            name='post_hashta_created_82297b_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_post_user_id_7a756f_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_post_created_910bcf_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_post_user_id_57d352_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_post_created_0713d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='postimage',
            name='post_postim_post_id_c0581b_idx',
        ),
        migrations.RemoveIndex(
            model_name='postimage',
            name='post_postim_post_id_a475e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpostfilter',
            name='post_userpo_user_id_041c31_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpostfilter',
            name='post_userpo_posts_t_c75266_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpostfilter',
            name='post_userpo_univers_034f0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpostfilter',
            name='post_userpo_departm_a9231f_idx',
        ),
    ]
