# Generated by Django 5.2.1 on 2025-07-14 23:22

import apps.post.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_hashtag_post_hashta_name_ac8446_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dosya Boyutu (bytes)'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='format',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Format (WEBP/JPEG)'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='hash',
            field=models.CharField(blank=True, help_text='Duplicate detection için', max_length=32, null=True, verbose_name='MD5 Hash'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='large',
            field=models.ImageField(blank=True, null=True, upload_to=apps.post.models.post_image_upload_path, verbose_name='Large (1200x1200)'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to=apps.post.models.post_image_upload_path, verbose_name='Medium (600x600)'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='original_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orijinal Yükseklik'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='original_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orijinal Genişlik'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='processed',
            field=models.BooleanField(default=False, help_text='Resim backend tarafından işlendi mi?', verbose_name='İşlenmiş'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.post.models.post_image_upload_path, verbose_name='Thumbnail (150x150)'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=apps.post.models.post_image_upload_path, verbose_name='Orijinal Resim'),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['hash'], name='post_postim_hash_bac10a_idx'),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['processed'], name='post_postim_process_92a9e0_idx'),
        ),
    ]
