# Generated by Django 5.2.1 on 2025-06-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_like_like_like_user_id_c1c775_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='like',
            name='like_like_user_id_c1c775_idx',
        ),
        migrations.RemoveIndex(
            model_name='like',
            name='like_like_content_8489e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='like',
            name='like_like_user_id_c03d60_idx',
        ),
    ]
