# Generated by Django 5.2 on 2025-04-09 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='İkon Sınıfı')),
            ],
            options={
                'verbose_name': 'Bildirim Türü',
                'verbose_name_plural': 'Bildirim Türleri',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='Metin')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtype', verbose_name='Bildirim Türü')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
