# Generated by Django 5.1.1 on 2025-05-01 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_notification_parent_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='parent_object_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
