# Generated by Django 5.1.1 on 2025-05-09 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatroom_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
    ]
