# Generated by Django 5.2.1 on 2025-06-11 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroomdeletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_active', 'updated_at'], name='chat_chatro_is_acti_3dedb9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_at'], name='chat_chatro_created_914abe_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroomdeletion',
            index=models.Index(fields=['chat_room', 'user', 'deleted_at'], name='chat_chatro_chat_ro_f22583_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'timestamp'], name='chat_messag_chat_ro_9355cd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'is_read'], name='chat_messag_chat_ro_450d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'timestamp'], name='chat_messag_sender__b20cde_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message', 'created_at'], name='chat_messag_message_a261d7_idx'),
        ),
    ]
