# Generated by Django 5.2.1 on 2025-06-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatroom_chat_chatro_is_acti_3dedb9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatroom',
            name='chat_chatro_is_acti_3dedb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatroom',
            name='chat_chatro_created_914abe_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatroomdeletion',
            name='chat_chatro_chat_ro_f22583_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_chat_ro_9355cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_chat_ro_450d5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__b20cde_idx',
        ),
        migrations.RemoveIndex(
            model_name='messageattachment',
            name='chat_messag_message_a261d7_idx',
        ),
    ]
